platform :ios, '8.4'

target 'app' do
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'OneSignal'
	pod 'Realm'

	pod 'IQAudioRecorderController'
	pod 'JSQMessagesViewController'
	pod 'MBProgressHUD'
	pod 'ProgressHUD'
	pod 'Reachability'
	pod 'RNGridMenu'
	pod 'SWTableViewCell'
end
